twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        # the value is the service's id
        global: '@App\Generator\GlobalGenerator'
when@test:
    twig:
        strict_variables: true
